version: 0.1
phases:
  install:
    commands:
      - npm install async path tmp fs
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket lambdapipeline
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
