AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A function is triggered off an upload to a bucket. It creates a thumbnail of the first pdf-page.
Resources:
  desnouckuploads:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: desnouckuploads

  CreateThumbnail:
    Type: AWS::Serverless::Function
    Properties:
      Handler: CreateThumbnail.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Policies: AmazonS3FullAccess
      MemorySize: 256
      Timeout: 5
      Events:
        PdfUpload:
          Type: S3
          Properties:
            Bucket: !Ref desnouckuploads
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  -
                    Name: suffix
                    Value: pdf
