AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A function is when SNS message is posted. Processec page of the PDF.
Resources:
  PDFPageThumbnail:
    Type: AWS::Serverless::Function
    Properties:
      Handler: PDFPageThumbnail.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Policies: AmazonS3FullAccess
      MemorySize: 256
      Timeout: 5
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: processPDF
